// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // `prisma generate` (run by every build) needs no database, so an unset
  // DATABASE_URL must not fail it: Workers Builds preview builds don't
  // receive the build variables. Commands that connect (migrate, db push)
  // still fail without it, on the empty URL.
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
