// Cloudflare Worker entry: the OpenNext build of the Next.js app, with an edge
// cache in front of the API routes. (The data crons run from GitHub Actions,
// see .github/workflows/cron.yml.)
//
// Vercel's CDN cached the API routes from their `Cache-Control: s-maxage`, so
// database reads grew with routes and cache windows, not visitors. Cloudflare
// does not cache a Worker's own responses from that header, so this does it
// with the Cache API: a hit is served without running the app or touching the
// database. The Cache API only works on a custom domain; on workers.dev every
// request runs the app.
// @ts-ignore: generated by `opennextjs-cloudflare build` (absent before it runs)
import { default as handler } from "./.open-next/worker.js";

type Ctx = { waitUntil(p: Promise<unknown>): void };

const sMaxAge = (cacheControl: string | null): number | null => {
  const match = cacheControl?.match(/(?:^|,)\s*s-maxage=(\d+)/i);
  return match ? Number(match[1]) : null;
};

const isCachedApi = (request: Request): boolean => {
  if (request.method !== "GET") return false;
  const { pathname } = new URL(request.url);
  return pathname.startsWith("/api/") && !pathname.startsWith("/api/cron/");
};

export default {
  async fetch(request: Request, env: unknown, ctx: Ctx): Promise<Response> {
    if (!isCachedApi(request)) return handler.fetch(request, env, ctx);

    const cache = (caches as unknown as { default: Cache }).default;
    const hit = await cache.match(request);
    if (hit) return hit;

    const response: Response = await handler.fetch(request, env, ctx);
    const seconds = sMaxAge(response.headers.get("cache-control"));
    if (response.status === 200 && seconds) {
      // The edge copy expires after s-maxage; the visitor's copy keeps the
      // route's own header.
      const copy = new Response(response.clone().body, response);
      copy.headers.set("cache-control", `public, max-age=${seconds}`);
      ctx.waitUntil(cache.put(request, copy));
    }
    return response;
  },
};
