// Cloudflare Worker entry: the OpenNext build of the Next.js app, with an edge
// cache in front of the API routes. (The data crons run from GitHub Actions,
// see .github/workflows/cron.yml.)
//
// Vercel's CDN cached the API routes from their `Cache-Control: s-maxage`, so
// database reads grew with routes and cache windows, not visitors. Cloudflare
// does not cache a Worker's own responses from that header, so this does it
// with the Cache API: a hit is served without running the app or touching the
// database.
//
// The import exists only after `opennextjs-cloudflare build`, so it needs an
// ignore directive that holds both before and after the build.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: generated by the OpenNext build
import { default as handler } from "./.open-next/worker.js";

type Ctx = { waitUntil(p: Promise<unknown>): void };

// The edge copy carries a max-age (the Cache API's expiry) in place of the
// route's own header, which rides along here and is restored on a hit, so a
// visitor gets the same Cache-Control from a hit as from a miss.
const ORIGIN_CACHE_CONTROL = "x-origin-cache-control";

const sMaxAge = (cacheControl: string | null): number | null => {
  const match = cacheControl?.match(/(?:^|,)\s*s-maxage=(\d+)/i);
  return match ? Number(match[1]) : null;
};

const isCachedApi = (request: Request): boolean => {
  if (request.method !== "GET") return false;
  const { pathname } = new URL(request.url);
  return pathname.startsWith("/api/") && !pathname.startsWith("/api/cron/");
};

const worker = {
  async fetch(request: Request, env: unknown, ctx: Ctx): Promise<Response> {
    if (!isCachedApi(request)) return handler.fetch(request, env, ctx);

    const cache = (caches as unknown as { default: Cache }).default;
    const hit = await cache.match(request);
    if (hit) {
      const response = new Response(hit.body, hit);
      const original = response.headers.get(ORIGIN_CACHE_CONTROL);
      if (original) response.headers.set("cache-control", original);
      response.headers.delete(ORIGIN_CACHE_CONTROL);
      return response;
    }

    const response: Response = await handler.fetch(request, env, ctx);
    const cacheControl = response.headers.get("cache-control");
    const seconds = sMaxAge(cacheControl);
    if (response.status === 200 && cacheControl && seconds) {
      // The edge copy expires after s-maxage.
      const copy = new Response(response.clone().body, response);
      copy.headers.set(ORIGIN_CACHE_CONTROL, cacheControl);
      copy.headers.set("cache-control", `public, max-age=${seconds}`);
      ctx.waitUntil(cache.put(request, copy));
    }
    return response;
  },
};

export default worker;
